import { Prize } from "./interface/Prize";
import { Task } from "./interface/Task";
export const ShowItem = {
  list: "list",
  chosen: "chosen",
};

export const getScore = (difficultyLevel: string) => {
  if (difficultyLevel === "Easy") return 1;
  if (difficultyLevel === "Medium") return 2;
  if (difficultyLevel === "Hard") return 3;
  return 0;
};

export const taskItems: Task[] = [
  {
    name: "Compliment a stranger",
    timeToComplete: 5,
    difficultyLevel: "Medium",
    category: "Social",
    completed: false,
  },
  {
    name: "Try a new hairstyle",
    timeToComplete: 30,
    difficultyLevel: "Easy",
    category: "Creative",
    completed: false,
  },
  {
    name: "Dance like no one’s watching",
    timeToComplete: 10,
    difficultyLevel: "Medium",
    category: "Physical",
    completed: false,
  },
  {
    name: "Share a personal story with a friend",
    timeToComplete: 15,
    difficultyLevel: "Hard",
    category: "Social",
    completed: false,
  },
  {
    name: "Create a vision board",
    timeToComplete: 45,
    difficultyLevel: "Easy",
    category: "Creative",
    completed: false,
  },
  {
    name: "Try a new workout or yoga pose",
    timeToComplete: 20,
    difficultyLevel: "Medium",
    category: "Physical",
    completed: false,
  },
  {
    name: "Give a small gift to someone unexpectedly",
    timeToComplete: 10,
    difficultyLevel: "Hard",
    category: "Social",
    completed: false,
  },
  {
    name: "Draw or paint something you’ve never tried before",
    timeToComplete: 60,
    difficultyLevel: "Medium",
    category: "Creative",
    completed: false,
  },
  {
    name: "Go for a walk without your phone",
    timeToComplete: 15,
    difficultyLevel: "Easy",
    category: "Self-Care",
    completed: false,
  },
  {
    name: "Plan a spontaneous outing with friends",
    timeToComplete: 30,
    difficultyLevel: "Hard",
    category: "Social",
    completed: false,
  },
  {
    name: "Write a poem about your day",
    timeToComplete: 20,
    difficultyLevel: "Medium",
    category: "Creative",
    completed: false,
  },
  {
    name: "Make a handmade gift for someone",
    timeToComplete: 60,
    difficultyLevel: "Hard",
    category: "Creative",
    completed: false,
  },
  {
    name: "Take a photo of something that inspires you",
    timeToComplete: 15,
    difficultyLevel: "Easy",
    category: "Creative",
    completed: false,
  },
  {
    name: "Try cooking or baking a new recipe",
    timeToComplete: 90,
    difficultyLevel: "Medium",
    category: "Creative",
    completed: false,
  },
  {
    name: "Create a short video or vlog about your hobby",
    timeToComplete: 45,
    difficultyLevel: "Hard",
    category: "Creative",
    completed: false,
  },
  {
    name: "Design your own piece of jewelry or accessory",
    timeToComplete: 60,
    difficultyLevel: "Medium",
    category: "Creative",
    completed: false,
  },
  {
    name: "Start a journal and write your first entry",
    timeToComplete: 30,
    difficultyLevel: "Easy",
    category: "Creative",
    completed: false,
  },
  {
    name: "Draw or paint a self-portrait",
    timeToComplete: 60,
    difficultyLevel: "Medium",
    category: "Creative",
    completed: false,
  },
  {
    name: "Write a short story using three random words",
    timeToComplete: 45,
    difficultyLevel: "Hard",
    category: "Creative",
    completed: false,
  },
  {
    name: "Create a playlist of songs that reflect your current mood",
    timeToComplete: 30,
    difficultyLevel: "Easy",
    category: "Creative",
    completed: false,
  },
  {
    name: "Go for a 30-minute run",
    timeToComplete: 30,
    difficultyLevel: "Hard",
    category: "Physical",
    completed: false,
  },
  {
    name: "Try a new dance routine from a YouTube video",
    timeToComplete: 20,
    difficultyLevel: "Medium",
    category: "Physical",
    completed: false,
  },
  {
    name: "Do a 10-minute meditation or yoga session",
    timeToComplete: 10,
    difficultyLevel: "Easy",
    category: "Physical",
    completed: false,
  },
  {
    name: "Go for a hike in a nearby park or trail",
    timeToComplete: 90,
    difficultyLevel: "Medium",
    category: "Physical",
    completed: false,
  },
  {
    name: "Try a new sport you’ve never played before",
    timeToComplete: 60,
    difficultyLevel: "Hard",
    category: "Physical",
    completed: false,
  },
  {
    name: "Do a 15-minute home workout using bodyweight exercises",
    timeToComplete: 15,
    difficultyLevel: "Medium",
    category: "Physical",
    completed: false,
  },
  {
    name: "Take a 5-minute cold shower",
    timeToComplete: 5,
    difficultyLevel: "Hard",
    category: "Physical",
    completed: false,
  },
  {
    name: "Go for a bike ride in your neighborhood",
    timeToComplete: 45,
    difficultyLevel: "Medium",
    category: "Physical",
    completed: false,
  },
  {
    name: "Practice deep breathing exercises for 5 minutes",
    timeToComplete: 5,
    difficultyLevel: "Easy",
    category: "Physical",
    completed: false,
  },
  {
    name: "Do 50 jumping jacks",
    timeToComplete: 5,
    difficultyLevel: "Medium",
    category: "Physical",
    completed: false,
  },
  {
    name: "Take a relaxing bath with candles and music",
    timeToComplete: 30,
    difficultyLevel: "Easy",
    category: "Self-Care",
    completed: false,
  },
  {
    name: "Read a book for 30 minutes",
    timeToComplete: 30,
    difficultyLevel: "Medium",
    category: "Self-Care",
    completed: false,
  },
  {
    name: "Spend 15 minutes journaling your thoughts",
    timeToComplete: 15,
    difficultyLevel: "Easy",
    category: "Self-Care",
    completed: false,
  },
  {
    name: "Try a new skincare routine",
    timeToComplete: 20,
    difficultyLevel: "Medium",
    category: "Self-Care",
    completed: false,
  },
  {
    name: "Do a digital detox for one hour",
    timeToComplete: 60,
    difficultyLevel: "Hard",
    category: "Self-Care",
    completed: false,
  },
  {
    name: "Cook a healthy meal for yourself",
    timeToComplete: 45,
    difficultyLevel: "Medium",
    category: "Self-Care",
    completed: false,
  },
  {
    name: "Practice mindfulness meditation for 10 minutes",
    timeToComplete: 10,
    difficultyLevel: "Easy",
    category: "Self-Care",
    completed: false,
  },
  {
    name: "Write a letter to your future self",
    timeToComplete: 30,
    difficultyLevel: "Medium",
    category: "Self-Care",
    completed: false,
  },
  {
    name: "Take a 20-minute nap",
    timeToComplete: 20,
    difficultyLevel: "Easy",
    category: "Self-Care",
    completed: false,
  },
  {
    name: "Plan a self-care day and list activities you want to do",
    timeToComplete: 25,
    difficultyLevel: "Medium",
    category: "Self-Care",
    completed: false,
  },
];

export const prizeItems: Prize[] = [
  { name: "Gift Card", score: 5 },
  { name: "Free Coffee", score: 10 },
  { name: "Movie Tickets", score: 30 },
  { name: "Discount Coupon", score: 15 },
  { name: "Book", score: 25 },
  { name: "Fitness Class Pass", score: 35 },
  { name: "Spa Voucher", score: 50 },
  { name: "Concert Tickets", score: 60 },
  { name: "Lunch with a Friend", score: 40 },
  { name: "New Gadgets", score: 100 },
];
